#!/usr/bin/env python3
r"""Regenerate the sanitized *.example.* templates from the live gitignored config.

WHY THIS EXISTS (2026-09-21)
----------------------------
Three operational config files are gitignored because they hold credentials:

    config/target_accounts.json   usernames / passwords / CVVs
    config/proxyIps.json          Bright Data customer id + zone password

Gitignored means *not backed up by a commit*. The code that reads them is in
git; the files themselves are on one disk. When the buyers moved to the home
line (all three `proxy_url=""`) and the monitor pool was trimmed 20 -> 8 on
2026-09-20, that architecture decision lived ONLY in those two files — a disk
failure would have restored the code and lost the configuration it needs.

`config/target_accounts.example.json` already existed for this reason but had
gone six weeks stale (last touched 2026-08-11), because nothing regenerated it.
So this script exists to be re-run, not to be a one-off:

    python tools/sync_config_templates.py            # rewrite the templates
    python tools/sync_config_templates.py --check    # CI/pre-commit: drifted?

WHAT SURVIVES vs WHAT DOES NOT
------------------------------
The templates keep every non-secret field verbatim — `proxy_url`, `timezone`,
`enabled`, `profile_dir`, `session_path`, the per-account `notes`, the pool's
`_comment_*` blocks. That is the expensive part: months of post-mortems about
which exits burned and why. Secrets become placeholders.

The templates are therefore a RECIPE, not a backup. They restore the shape and
the reasoning; you refill the secrets from a password manager. For the real
values off this machine, copy the two live files somewhere that is not this
disk, e.g.:

    copy config\target_accounts.json %USERPROFILE%\OneDrive\botconfig\
    copy config\proxyIps.json        %USERPROFILE%\OneDrive\botconfig\

They are small, they change rarely, and they are the only two files a rebuild
cannot reconstruct from git.

NOTE ON THE EXIT IPs: they stay in the template in clear. They are already in
this public repo's history, the `_comment_*` text names them individually
("excluded for cause: 168.158.143.27 (404 ban)"), and redacting the list while
the prose discusses it would gut the document. Without the BD credential they
are inert. If that tradeoff stops being acceptable, the repo should go private
rather than the template go lossy.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Per-account fields that are genuinely secret. Everything else is operational
# state we WANT preserved in git.
ACCOUNT_SECRET_FIELDS = {
    'username': '__ACCOUNT_EMAIL__',
    'password': '__ACCOUNT_PASSWORD__',
    'cvv': '__CARD_CVV__',
}

# http://brd-customer-<customer>-zone-<zone>-ip-<ip>:<password>@host:port
_BD_URL_RE = re.compile(
    r'(?P<scheme>\w+://)'
    r'brd-customer-(?P<customer>[^-]+)-zone-(?P<rest>.*?)'
    r':(?P<password>[^@]+)@(?P<host>.+)'
)

BD_CUSTOMER_PLACEHOLDER = '__BD_CUSTOMER__'
BD_PASSWORD_PLACEHOLDER = '__BD_ZONE_PASSWORD__'

BANNER = ('THIS FILE IS GENERATED by tools/sync_config_templates.py — do not '
          'hand-edit. Secrets are placeholders (__LIKE_THIS__); every other '
          'field is the real operational value, preserved so the config can be '
          'rebuilt from scratch. Copy to the real filename, refill the '
          'placeholders, and it works.')


def _sanitize_proxy_url(url: str) -> str:
    """Strip the BD customer id and zone password out of one proxy URL."""
    m = _BD_URL_RE.match(url)
    if not m:
        # Unknown shape — redact everything between '//' and '@' rather than
        # risk passing a credential through untouched.
        return re.sub(r'//[^@/]+@', f'//{BD_PASSWORD_PLACEHOLDER}@', url)
    return (f"{m.group('scheme')}brd-customer-{BD_CUSTOMER_PLACEHOLDER}"
            f"-zone-{m.group('rest')}:{BD_PASSWORD_PLACEHOLDER}@{m.group('host')}")


def build_accounts_template(live: dict) -> dict:
    out = {'_GENERATED': BANNER}
    for key, value in live.items():
        if key != 'accounts':
            out[key] = value
    accounts = []
    for acct in live.get('accounts', []):
        clean = {}
        for k, v in acct.items():
            clean[k] = ACCOUNT_SECRET_FIELDS[k] if k in ACCOUNT_SECRET_FIELDS else v
        accounts.append(clean)
    out['accounts'] = accounts
    return out


def build_proxies_template(live: dict) -> dict:
    out = {'_GENERATED': BANNER}
    for key, value in live.items():
        if isinstance(value, list) and value and isinstance(value[0], str):
            out[key] = [_sanitize_proxy_url(u) for u in value]
        else:
            out[key] = value
    return out



def _write(path: Path, content: str, check: bool) -> bool:
    """Return True if the file is already up to date."""
    existing = path.read_text(encoding='utf-8') if path.exists() else None
    if existing == content:
        print(f"  ok       {path.relative_to(REPO)}")
        return True
    if check:
        state = 'MISSING' if existing is None else 'STALE'
        print(f"  {state:8} {path.relative_to(REPO)}")
        return False
    path.write_text(content, encoding='utf-8')
    print(f"  {'wrote':8} {path.relative_to(REPO)}")
    return False


def _assert_no_secrets(content: str, live_secrets: list) -> None:
    """Last line of defence: no real secret may appear in a template."""
    for secret in live_secrets:
        if secret and len(str(secret)) >= 4 and str(secret) in content:
            raise SystemExit(
                f"REFUSING TO WRITE: a live secret leaked into the template "
                f"(value starting '{str(secret)[:2]}...'). Fix the redaction "
                f"rules in {Path(__file__).name} before re-running.")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--check', action='store_true',
                    help='report drift and exit non-zero; write nothing')
    args = ap.parse_args()

    jobs = []
    secrets: list = []

    accounts_live = REPO / 'config' / 'target_accounts.json'
    if accounts_live.exists():
        live = json.loads(accounts_live.read_text(encoding='utf-8'))
        for acct in live.get('accounts', []):
            secrets.extend(acct.get(f) for f in ACCOUNT_SECRET_FIELDS)
        jobs.append((REPO / 'config' / 'target_accounts.example.json',
                     json.dumps(build_accounts_template(live), indent=2,
                                ensure_ascii=False) + '\n'))

    proxies_live = REPO / 'config' / 'proxyIps.json'
    if proxies_live.exists():
        live = json.loads(proxies_live.read_text(encoding='utf-8'))
        for group in live.values():
            if isinstance(group, list):
                for url in group:
                    m = _BD_URL_RE.match(url) if isinstance(url, str) else None
                    if m:
                        secrets.extend([m.group('password'), m.group('customer')])
        jobs.append((REPO / 'config' / 'proxyIps.example.json',
                     json.dumps(build_proxies_template(live), indent=2,
                                ensure_ascii=False) + '\n'))

    if not jobs:
        print('No live config files found — nothing to do.')
        return 0

    print('Config templates:' if not args.check else 'Config templates (check):')
    all_fresh = True
    for path, content in jobs:
        _assert_no_secrets(content, secrets)
        all_fresh &= _write(path, content, args.check)

    if args.check and not all_fresh:
        print('\nTemplates are out of sync with the live config.\n'
              'Run: python tools/sync_config_templates.py  (then commit)')
        return 1
    if not args.check:
        print('\nCommit the templates. The REAL values live on this disk'
              ' ONLY — copy config/target_accounts.json and'
              ' config/proxyIps.json somewhere off-machine'
              ' (OneDrive, a USB stick, a password manager).')
    return 0


if __name__ == '__main__':
    sys.exit(main())
